import type {
  AnalyticsSnapshot,
  Event,
  FeedPost,
  Job,
  MessageThread,
  NotificationItem,
  Profile,
} from "@/types/domain";

const now = new Date();
const iso = (daysOffset: number) => new Date(now.getTime() + daysOffset * 86_400_000).toISOString();

export const demoProfiles: Profile[] = [
  {
    id: "student-1",
    fullName: "Aarav Mehta",
    email: "aarav@student.connectly.edu",
    avatarUrl: null,
    role: "STUDENT",
    status: "ACTIVE",
    department: "Computer Science",
    graduationYear: 2027,
    studentId: "CS2027-041",
    bio: "Final year student focused on full-stack engineering, machine learning, and product design.",
    company: null,
    designation: "Student",
    industry: "Software",
    city: "Bengaluru",
    country: "India",
    skills: ["React", "TypeScript", "Python", "Machine Learning", "PostgreSQL"],
    interests: ["Machine Learning", "Product Engineering", "Startups"],
    careerGoals: "Become a product-minded software engineer and contribute to AI-powered education tools.",
    technologyStack: ["React", "Node.js", "Supabase", "Python"],
    achievements: ["Built a campus placement tracker", "Finalist in Smart India Hackathon college round"],
    projects: ["Connectly FYP", "AI Resume Analyzer"],
    socialLinks: { github: "https://github.com/connectly-demo" },
    academicTitle: null,
    publications: [],
    researchInterests: [],
    isMentor: false,
    mentorCategories: [],
    mentorshipCapacity: 0,
    profileCompleteness: 82,
    phoneVisible: false,
    phone: null,
    createdAt: iso(-60),
    updatedAt: iso(-1),
  },
  {
    id: "alumni-1",
    fullName: "Nisha Rao",
    email: "nisha.rao@example.com",
    avatarUrl: null,
    role: "ALUMNI",
    status: "ACTIVE",
    department: "Computer Science",
    graduationYear: 2018,
    studentId: null,
    bio: "Senior software engineer building collaboration products at scale. Loves mentoring students on interviews and real-world engineering habits.",
    company: "Atlassian",
    designation: "Senior Software Engineer",
    industry: "Software",
    city: "Bengaluru",
    country: "India",
    skills: ["React", "TypeScript", "System Design", "PostgreSQL", "Mentoring"],
    interests: ["Developer Tools", "Career Guidance", "Machine Learning"],
    careerGoals: null,
    technologyStack: ["React", "GraphQL", "PostgreSQL", "AWS"],
    achievements: ["Scaled internal design systems to 200+ engineers", "Mentored 40+ students"],
    projects: ["Campus Alumni Connect", "Design System Migration"],
    socialLinks: { linkedin: "https://linkedin.com" },
    academicTitle: null,
    publications: [],
    researchInterests: [],
    isMentor: true,
    mentorCategories: ["Career Guidance", "Mock Interview", "Resume Review"],
    mentorshipCapacity: 6,
    profileCompleteness: 96,
    phoneVisible: false,
    phone: null,
    createdAt: iso(-240),
    updatedAt: iso(-2),
  },
  {
    id: "alumni-2",
    fullName: "Rohan Iyer",
    email: "rohan.iyer@example.com",
    avatarUrl: null,
    role: "ALUMNI",
    status: "ACTIVE",
    department: "Information Technology",
    graduationYear: 2017,
    studentId: null,
    bio: "Data platform engineer working on recommendation systems and analytics pipelines.",
    company: "Razorpay",
    designation: "Lead Data Engineer",
    industry: "FinTech",
    city: "Mumbai",
    country: "India",
    skills: ["Python", "Machine Learning", "Data Engineering", "SQL", "Spark"],
    interests: ["FinTech", "Machine Learning", "Career Guidance"],
    careerGoals: null,
    technologyStack: ["Python", "Spark", "PostgreSQL", "Airflow"],
    achievements: ["Built fraud analytics pipelines", "Speaker at campus data day"],
    projects: ["Transaction Risk Monitor"],
    socialLinks: { linkedin: "https://linkedin.com" },
    academicTitle: null,
    publications: [],
    researchInterests: [],
    isMentor: true,
    mentorCategories: ["Project Advice", "Career Guidance", "Higher Studies"],
    mentorshipCapacity: 4,
    profileCompleteness: 91,
    phoneVisible: true,
    phone: "+91 90000 00000",
    createdAt: iso(-300),
    updatedAt: iso(-4),
  },
  {
    id: "faculty-1",
    fullName: "Dr. Meera Sharma",
    email: "meera.sharma@connectly.edu",
    avatarUrl: null,
    role: "FACULTY",
    status: "ACTIVE",
    department: "Computer Science",
    graduationYear: null,
    studentId: null,
    bio: "Professor and placement mentor researching human-centered machine learning and student employability.",
    company: "Connectly University",
    designation: "Professor",
    industry: "Research",
    city: "Pune",
    country: "India",
    skills: ["Machine Learning", "Research", "Python", "Mentoring"],
    interests: ["Research Guidance", "Higher Studies", "Placements"],
    careerGoals: null,
    technologyStack: ["Python", "TensorFlow", "PostgreSQL"],
    achievements: ["Published 30+ research papers", "Placement cell faculty coordinator"],
    projects: ["Student Skill Graph"],
    socialLinks: {},
    academicTitle: "Professor",
    publications: ["Human-centered models for student success", "Explainable recommender systems"],
    researchInterests: ["Machine Learning", "Education Technology", "Responsible AI"],
    isMentor: true,
    mentorCategories: ["Research Guidance", "Higher Studies", "Project Advice"],
    mentorshipCapacity: 8,
    profileCompleteness: 94,
    phoneVisible: false,
    phone: null,
    createdAt: iso(-420),
    updatedAt: iso(-3),
  },
  {
    id: "admin-1",
    fullName: "Priya Menon",
    email: "admin@connectly.edu",
    avatarUrl: null,
    role: "ADMIN",
    status: "ACTIVE",
    department: "Placement Cell",
    graduationYear: null,
    studentId: null,
    bio: "Admin for alumni relations, placements, and university engagement programs.",
    company: "Connectly University",
    designation: "Alumni Relations Officer",
    industry: "Education",
    city: "Pune",
    country: "India",
    skills: ["Operations", "Engagement", "Analytics"],
    interests: ["Alumni Relations", "Placement Support"],
    careerGoals: null,
    technologyStack: [],
    achievements: ["Organized 20+ alumni engagement events"],
    projects: [],
    socialLinks: {},
    academicTitle: null,
    publications: [],
    researchInterests: [],
    isMentor: false,
    mentorCategories: [],
    mentorshipCapacity: 0,
    profileCompleteness: 88,
    phoneVisible: false,
    phone: null,
    createdAt: iso(-180),
    updatedAt: iso(-2),
  },
];

export const demoJobs: Job[] = [
  {
    id: "job-1",
    title: "Frontend Engineering Internship",
    organization: "Atlassian",
    location: "Bengaluru / Remote",
    type: "INTERNSHIP",
    deadline: iso(18),
    skills: ["React", "TypeScript", "Testing"],
    description: "Work with a product engineering team on collaboration experiences, accessibility, and component quality.",
    postedBy: "Nisha Rao",
    status: "PUBLISHED",
    createdAt: iso(-3),
  },
  {
    id: "job-2",
    title: "Research Assistant - ML for Education",
    organization: "Connectly University",
    location: "Pune",
    type: "RESEARCH",
    deadline: iso(25),
    skills: ["Python", "Machine Learning", "Research"],
    description: "Assist faculty on student skill graph research and prototype evaluation dashboards.",
    postedBy: "Dr. Meera Sharma",
    status: "PUBLISHED",
    createdAt: iso(-6),
  },
  {
    id: "job-3",
    title: "Backend Referral - Data Platform",
    organization: "Razorpay",
    location: "Mumbai",
    type: "REFERRAL",
    deadline: iso(12),
    skills: ["Python", "SQL", "Data Engineering"],
    description: "Alumni referral for backend/data roles. Strong SQL and distributed systems fundamentals preferred.",
    postedBy: "Rohan Iyer",
    status: "PUBLISHED",
    createdAt: iso(-7),
  },
];

export const demoEvents: Event[] = [
  {
    id: "event-1",
    title: "Alumni Mentorship Evening",
    type: "MENTORSHIP_SESSION",
    startsAt: iso(8),
    endsAt: iso(8),
    location: "Seminar Hall A",
    description: "Small-group conversations with alumni mentors across software, research, and product roles.",
    bannerUrl: null,
    capacity: 120,
    registrations: 86,
    createdBy: "Priya Menon",
  },
  {
    id: "event-2",
    title: "Resume Review Workshop",
    type: "WORKSHOP",
    startsAt: iso(14),
    endsAt: iso(14),
    location: "Online",
    description: "Faculty and alumni reviewers help students improve resumes for placements and internships.",
    bannerUrl: null,
    capacity: 80,
    registrations: 52,
    createdBy: "Dr. Meera Sharma",
  },
  {
    id: "event-3",
    title: "Class of 2018 Reunion",
    type: "REUNION",
    startsAt: iso(35),
    endsAt: iso(35),
    location: "University Auditorium",
    description: "A focused reunion with networking, student interaction, and alumni recognition.",
    bannerUrl: null,
    capacity: 220,
    registrations: 141,
    createdBy: "Priya Menon",
  },
];

export const demoFeedPosts: FeedPost[] = [
  {
    id: "post-1",
    authorName: "Priya Menon",
    authorRole: "ADMIN",
    type: "PLACEMENT",
    title: "Placement mentorship sprint begins this week",
    content: "Students can now request resume reviews and mock interviews from verified alumni mentors.",
    likes: 42,
    comments: 8,
    createdAt: iso(-1),
  },
  {
    id: "post-2",
    authorName: "Dr. Meera Sharma",
    authorRole: "FACULTY",
    type: "RESEARCH",
    title: "Faculty research group opens student assistant applications",
    content: "The ML for Education group is inviting applications for research assistants from final year students.",
    likes: 31,
    comments: 5,
    createdAt: iso(-2),
  },
  {
    id: "post-3",
    authorName: "Nisha Rao",
    authorRole: "ALUMNI",
    type: "ACHIEVEMENT",
    title: "Alumni spotlight: design systems at scale",
    content: "Nisha shared a walkthrough of building maintainable frontend systems for large teams.",
    likes: 58,
    comments: 12,
    createdAt: iso(-5),
  },
];

export const demoNotifications: NotificationItem[] = [
  {
    id: "notification-1",
    title: "Mentor recommendation ready",
    body: "Nisha Rao is a 94% match for your career goals and skills.",
    read: false,
    createdAt: iso(-1),
  },
  {
    id: "notification-2",
    title: "Event RSVP confirmed",
    body: "You are registered for Alumni Mentorship Evening.",
    read: true,
    createdAt: iso(-2),
  },
];

export const demoThreads: MessageThread[] = [
  {
    id: "thread-1",
    title: "Mentorship with Nisha Rao",
    participantNames: ["Aarav Mehta", "Nisha Rao"],
    lastMessage: "Please share your resume and the roles you are targeting.",
    updatedAt: iso(-1),
  },
  {
    id: "thread-2",
    title: "Research guidance",
    participantNames: ["Aarav Mehta", "Dr. Meera Sharma"],
    lastMessage: "We can discuss your ML project proposal after the workshop.",
    updatedAt: iso(-3),
  },
];

export const demoAnalytics: AnalyticsSnapshot = {
  totalUsers: 1248,
  activeMentors: 186,
  pendingApprovals: 24,
  openJobs: 38,
  eventRegistrations: 512,
  monthlyEngagement: [
    { month: "Jan", users: 620, mentorship: 42, jobs: 18 },
    { month: "Feb", users: 720, mentorship: 56, jobs: 21 },
    { month: "Mar", users: 820, mentorship: 71, jobs: 27 },
    { month: "Apr", users: 1030, mentorship: 94, jobs: 33 },
    { month: "May", users: 1248, mentorship: 126, jobs: 38 },
  ],
};
